// <auto-generated />
using System;
using Amet.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amet.Core.Migrations
{
    [DbContext(typeof(AmetDbContext))]
    partial class AmetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amet.Core.Models.Acta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConductorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHecho")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimitePago")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IdentificacionPendiente")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoRecargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reincidente")
                        .HasColumnType("bit");

                    b.Property<int>("TipoInfraccionId")
                        .HasColumnType("int");

                    b.Property<string>("UrlEvidencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("TipoInfraccionId");

                    b.ToTable("Actas");
                });

            modelBuilder.Entity("Amet.Core.Models.Canodromo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminIngresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminSalidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiasCobrados")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActaId");

                    b.HasIndex("AdminIngresoId");

                    b.HasIndex("AdminSalidaId");

                    b.ToTable("Canodromos");
                });

            modelBuilder.Entity("Amet.Core.Models.Conductor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IdentificacionPendiente")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("Amet.Core.Models.Impugnacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FiscalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MontoNuevo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoCiudadano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActaId");

                    b.HasIndex("FiscalId");

                    b.ToTable("Impugnaciones");
                });

            modelBuilder.Entity("Amet.Core.Models.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CajeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoEstadia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoMulta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoRecargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroTransaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActaId");

                    b.HasIndex("CajeroId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Amet.Core.Models.TipoInfraccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoCarga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoMotocicleta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoParticular")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiereRetencion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TiposInfraccion");
                });

            modelBuilder.Entity("Amet.Core.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Amet.Core.Models.Acta", b =>
                {
                    b.HasOne("Amet.Core.Models.Usuario", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Amet.Core.Models.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId");

                    b.HasOne("Amet.Core.Models.TipoInfraccion", "TipoInfraccion")
                        .WithMany()
                        .HasForeignKey("TipoInfraccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Conductor");

                    b.Navigation("TipoInfraccion");
                });

            modelBuilder.Entity("Amet.Core.Models.Canodromo", b =>
                {
                    b.HasOne("Amet.Core.Models.Acta", "Acta")
                        .WithMany()
                        .HasForeignKey("ActaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amet.Core.Models.Usuario", "AdminIngreso")
                        .WithMany()
                        .HasForeignKey("AdminIngresoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Amet.Core.Models.Usuario", "AdminSalida")
                        .WithMany()
                        .HasForeignKey("AdminSalidaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Acta");

                    b.Navigation("AdminIngreso");

                    b.Navigation("AdminSalida");
                });

            modelBuilder.Entity("Amet.Core.Models.Impugnacion", b =>
                {
                    b.HasOne("Amet.Core.Models.Acta", "Acta")
                        .WithMany()
                        .HasForeignKey("ActaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amet.Core.Models.Usuario", "Fiscal")
                        .WithMany()
                        .HasForeignKey("FiscalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Acta");

                    b.Navigation("Fiscal");
                });

            modelBuilder.Entity("Amet.Core.Models.Pago", b =>
                {
                    b.HasOne("Amet.Core.Models.Acta", "Acta")
                        .WithMany()
                        .HasForeignKey("ActaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amet.Core.Models.Usuario", "Cajero")
                        .WithMany()
                        .HasForeignKey("CajeroId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Acta");

                    b.Navigation("Cajero");
                });
#pragma warning restore 612, 618
        }
    }
}
